## 1. Import libraries

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

## 2. Load dataset

In [2]:
raw_df=pd.read_csv("vitamin_deficiency_disease_dataset.csv")  # Read the raw dataset
raw_df

,age,gender,bmi,smoking_status,alcohol_consumption,exercise_level,diet_type,sun_exposure,income_level,latitude_region,...,has_night_blindness,has_fatigue,has_bleeding_gums,has_bone_pain,has_muscle_weakness,has_numbness_tingling,has_memory_problems,has_pale_skin,disease_diagnosis,has_multiple_deficiencies
0,79,Male,24.8,Former,NaN,Active,Vegetarian,High,High,Mid,...,0,0,0,0,0,0,0,0,Healthy,0
1,77,Female,39.9,Former,Moderate,Light,Omnivore,Low,Low,Low,...,0,0,0,1,0,0,0,0,Rickets_Osteomalacia,0
2,24,Male,26.4,Former,Heavy,Moderate,Omnivore,Low,High,High,...,1,0,0,0,0,0,0,0,Healthy,0
3,69,Male,23.1,Never,Heavy,Moderate,Vegetarian,High,Low,Low,...,0,0,0,0,0,1,1,0,Anemia,0
4,63,Male,29.6,Never,NaN,Moderate,Vegetarian,Moderate,High,Low,...,0,0,0,0,0,0,0,0,Healthy,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,25,Female,21.6,Former,Heavy,Active,Pescatarian,Moderate,Middle,High,...,1,0,0,0,0,0,0,0,Healthy,0
3996,50,Male,29.5,Former,Moderate,Sedentary,Vegetarian,Low,High,Low,...,0,0,0,0,0,0,0,0,Healthy,0
3997,34,Female,24.8,Never,NaN,Active,Pescatarian,Moderate,Low,Low,...,0,1,0,0,0,1,1,0,Anemia,0
3998,39,Female,26.9,Former,Heavy,Active,Omnivore,High,Low,High,...,1,0,0,0,0,0,0,0,Anemia,0
3999,41,Female,28.0,Current,NaN,Sedentary,Omnivore,High,High,High,...,0,0,0,0,0,0,1,0,Anemia,0

## 3. Getting basic information about the dataset

In [3]:
# View basic structure
raw_df.shape

(4000, 34)

In [4]:
# Check column types and missing values
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        4000 non-null   int64
 1   gender                     4000 non-null   object
 2   bmi                        4000 non-null   float64
 3   smoking_status             4000 non-null   object
 4   alcohol_consumption        2722 non-null   object
 5   exercise_level             4000 non-null   object
 6   diet_type                  4000 non-null   object
 7   sun_exposure               4000 non-null   object
 8   income_level               4000 non-null   object
 9   latitude_region            4000 non-null   object
 10  vitamin_a_percent_rda      4000 non-null   float64
 11  vitamin_c_percent_rda      4000 non-null   float64
 12  vitamin_d_percent_rda      4000 non-null   float64
 13  vitamin_e_percent_rda      4000 non-null   float64
 14  vitamin_b12_percent_rda    4000 non-null   float64
 15  folate_percent_rda         4000 non-null   float64
 16  calcium_percent_rda        4000 non-null   float64
 17  iron_percent_rda           4000 non-null   float64
 18  hemoglobin_g_dl            4000 non-null   float64
 19  serum_vitamin_d_ng_ml      4000 non-null   float64
 20  serum_vitamin_b12_pg_ml    4000 non-null   float64
 21  serum_folate_ng_ml         4000 non-null   float64
 22  symptoms_count             4000 non-null   int64
 23  symptoms_list              2672 non-null   object
 24  has_night_blindness        4000 non-null   int64
 25  has_fatigue                4000 non-null   int64
 26  has_bleeding_gums          4000 non-null   int64
 27  has_bone_pain              4000 non-null   int64
 28  has_muscle_weakness        4000 non-null   int64
 29  has_numbness_tingling      4000 non-null   int64
 30  has_memory_problems        4000 non-null   int64
 31  has_pale_skin              4000 non-null   int64
 32  disease_diagnosis          4000 non-null   object
 33  has_multiple_deficiencies  4000 non-null   int64
dtypes: float64(13), int64(11), object(10)
memory usage: 1.0+ MB

In [5]:
# Statistical summary
raw_df.describe()

,age,bmi,vitamin_a_percent_rda,vitamin_c_percent_rda,vitamin_d_percent_rda,vitamin_e_percent_rda,vitamin_b12_percent_rda,folate_percent_rda,calcium_percent_rda,iron_percent_rda,...,symptoms_count,has_night_blindness,has_fatigue,has_bleeding_gums,has_bone_pain,has_muscle_weakness,has_numbness_tingling,has_memory_problems,has_pale_skin,has_multiple_deficiencies
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,...,4000.00000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000
mean,50.766250,26.105325,90.770850,89.199075,72.216388,89.946125,62.743225,90.382275,82.586300,76.211125,...,1.86725,0.102250,0.269250,0.043500,0.300750,0.265750,0.351250,0.303000,0.161750,0.347250
std,19.306237,4.922746,37.083534,37.505809,42.831000,37.444649,37.396636,37.563684,36.359131,33.226984,...,1.79581,0.303015,0.443626,0.204005,0.458641,0.441787,0.477421,0.459613,0.368267,0.476156
min,18.000000,15.000000,10.000000,10.000000,7.000000,10.000000,10.000000,10.000000,10.000000,10.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,34.000000,22.800000,62.600000,60.975000,40.730000,61.700000,32.700000,61.800000,55.600000,51.400000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,51.000000,26.200000,85.500000,83.500000,62.270000,84.050000,55.600000,84.800000,77.100000,71.250000,...,2.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,67.000000,29.400000,115.300000,113.000000,93.317500,114.100000,84.500000,115.200000,105.300000,95.900000,...,3.00000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000
max,84.000000,45.000000,219.000000,250.000000,275.600000,237.600000,243.600000,226.600000,232.700000,211.400000,...,9.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
# Check null values
print(raw_df.isnull().sum())

age                             0
gender                          0
bmi                             0
smoking_status                  0
alcohol_consumption          1278
exercise_level                  0
diet_type                       0
sun_exposure                    0
income_level                    0
latitude_region                 0
vitamin_a_percent_rda           0
vitamin_c_percent_rda           0
vitamin_d_percent_rda           0
vitamin_e_percent_rda           0
vitamin_b12_percent_rda         0
folate_percent_rda              0
calcium_percent_rda             0
iron_percent_rda                0
hemoglobin_g_dl                 0
serum_vitamin_d_ng_ml           0
serum_vitamin_b12_pg_ml         0
serum_folate_ng_ml              0
symptoms_count                  0
symptoms_list                1328
has_night_blindness             0
has_fatigue                     0
has_bleeding_gums               0
has_bone_pain                   0
has_muscle_weakness             0
has_numbness_tingling           0
has_memory_problems             0
has_pale_skin                   0
disease_diagnosis               0
has_multiple_deficiencies       0
dtype: int64

## 4. Data Pre-Processing

### 4.1. Drop Irrelevant Columns

In [7]:
raw_df = raw_df.drop('has_multiple_deficiencies', axis=1)
raw_df = raw_df.drop('symptoms_list', axis=1)

### 4.2. Explore Categorical Features

In [8]:
print(raw_df['gender'].value_counts())
print(raw_df['smoking_status'].value_counts())
print(raw_df['exercise_level'].value_counts())
print(raw_df['diet_type'].value_counts())

gender
Male      2029
Female    1971
Name: count, dtype: int64
smoking_status
Never      1344
Current    1335
Former     1321
Name: count, dtype: int64
exercise_level
Sedentary    1033
Light         996
Moderate      990
Active        981
Name: count, dtype: int64
diet_type
Vegan          1017
Vegetarian      999
Omnivore        993
Pescatarian     991
Name: count, dtype: int64

### 4.3. One-Hot Encoding (Categorical variables)

In [9]:
# Convert categorical columns into numerical format
raw_df = pd.get_dummies(raw_df,columns=['gender', 'smoking_status', 'exercise_level', 'diet_type'],drop_first=True)   # avoid redundancy
raw_df

,age,bmi,alcohol_consumption,sun_exposure,income_level,latitude_region,vitamin_a_percent_rda,vitamin_c_percent_rda,vitamin_d_percent_rda,vitamin_e_percent_rda,...,disease_diagnosis,gender_Male,smoking_status_Former,smoking_status_Never,exercise_level_Light,exercise_level_Moderate,exercise_level_Sedentary,diet_type_Pescatarian,diet_type_Vegan,diet_type_Vegetarian
0,79,24.8,NaN,High,High,Mid,119.1,147.3,152.88,97.5,...,Healthy,True,True,False,False,False,False,False,False,True
1,77,39.9,Moderate,Low,Low,Low,85.7,57.5,32.76,82.7,...,Rickets_Osteomalacia,False,True,False,True,False,False,False,False,False
2,24,26.4,Heavy,Low,High,High,48.3,152.1,94.99,169.3,...,Healthy,True,True,False,False,True,False,False,False,False
3,69,23.1,Heavy,High,Low,Low,75.8,51.0,51.48,85.7,...,Anemia,True,False,True,False,True,False,False,False,True
4,63,29.6,NaN,Moderate,High,Low,93.3,111.5,62.90,155.6,...,Healthy,True,False,True,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,25,21.6,Heavy,Moderate,Middle,High,41.4,66.1,111.50,99.8,...,Healthy,False,True,False,False,False,False,True,False,False
3996,50,29.5,Moderate,Low,High,Low,146.3,113.0,72.66,91.5,...,Healthy,True,True,False,False,False,True,False,False,True
3997,34,24.8,NaN,Moderate,Low,Low,77.0,39.8,76.10,43.2,...,Anemia,False,False,True,False,False,False,True,False,False
3998,39,26.9,Heavy,High,Low,High,41.1,71.2,75.79,32.5,...,Anemia,False,True,False,False,False,False,False,False,False
3999,41,28.0,NaN,High,High,High,135.6,63.7,155.61,170.0,...,Anemia,False,False,False,False,False,True,False,False,False

### 4.4. Label Encoding (Ordinal columns)

In [10]:
le = LabelEncoder()
cols = ['alcohol_consumption', 'sun_exposure', 'income_level', 'latitude_region']
for col in cols:
    raw_df[col] = le.fit_transform(raw_df[col])

### 4.5. Encode Target Variable

In [11]:
raw_df['disease_diagnosis'] = le.fit_transform(raw_df['disease_diagnosis'])

### 4.6. Convert Boolean to Integer

In [12]:
# Convert True/False → 1/0
bool_cols = raw_df.select_dtypes(include='bool').columns
raw_df[bool_cols] = raw_df[bool_cols].astype(int)

### 4.7. Final Check

In [13]:
print(raw_df.head())
print(raw_df.dtypes)

   age   bmi  alcohol_consumption  sun_exposure  income_level  \
0   79  24.8                    2             0             0
1   77  39.9                    1             1             1
2   24  26.4                    0             1             0
3   69  23.1                    0             0             1
4   63  29.6                    2             2             0

   latitude_region  vitamin_a_percent_rda  vitamin_c_percent_rda  \
0                2                  119.1                  147.3
1                1                   85.7                   57.5
2                0                   48.3                  152.1
3                1                   75.8                   51.0
4                1                   93.3                  111.5

   vitamin_d_percent_rda  vitamin_e_percent_rda  ...  disease_diagnosis  \
0                 152.88                   97.5  ...                  1
1                  32.76                   82.7  ...                  3
2                  94.99                  169.3  ...                  1
3                  51.48                   85.7  ...                  0
4                  62.90                  155.6  ...                  1

   gender_Male  smoking_status_Former  smoking_status_Never  \
0            1                      1                     0
1            0                      1                     0
2            1                      1                     0
3            1                      0                     1
4            1                      0                     1

   exercise_level_Light  exercise_level_Moderate  exercise_level_Sedentary  \
0                     0                        0                         0
1                     1                        0                         0
2                     0                        1                         0
3                     0                        1                         0
4                     0                        1                         0

   diet_type_Pescatarian  diet_type_Vegan  diet_type_Vegetarian
0                      0                0                     1
1                      0                0                     0
2                      0                0                     0
3                      0                0                     1
4                      0                0                     1

[5 rows x 37 columns]
age                           int64
bmi                         float64
alcohol_consumption           int64
sun_exposure                  int64
income_level                  int64
latitude_region               int64
vitamin_a_percent_rda       float64
vitamin_c_percent_rda       float64
vitamin_d_percent_rda       float64
vitamin_e_percent_rda       float64
vitamin_b12_percent_rda     float64
folate_percent_rda          float64
calcium_percent_rda         float64
iron_percent_rda            float64
hemoglobin_g_dl             float64
serum_vitamin_d_ng_ml       float64
serum_vitamin_b12_pg_ml     float64
serum_folate_ng_ml          float64
symptoms_count                int64
has_night_blindness           int64
has_fatigue                   int64
has_bleeding_gums             int64
has_bone_pain                 int64
has_muscle_weakness           int64
has_numbness_tingling         int64
has_memory_problems           int64
has_pale_skin                 int64
disease_diagnosis             int64
gender_Male                   int64
smoking_status_Former         int64
smoking_status_Never          int64
exercise_level_Light          int64
exercise_level_Moderate       int64
exercise_level_Sedentary      int64
diet_type_Pescatarian         int64
diet_type_Vegan               int64
diet_type_Vegetarian          int64
dtype: object

In [15]:
raw_df.to_csv("preprocessed_data.csv", index=False)